### ISSUE TITLE
virer le menu au rollover sur le pseudo du menu quand on est logué

### ISSUE THREAD

**Issue by raphael-g** [loult-elte-fwere/loult-bnl-client#1]
https://image.noelshack.com/fichiers/2021/23/6/1623504982-capture-d-ecran-2021-06-12-a-15-35-49.png

**Comment by raphael-g** [comment]
et celui là aussi 
https://image.noelshack.com/fichiers/2021/23/6/1623505133-capture-d-ecran-2021-06-12-a-15-38-18.png

**Comment by hadware** [comment]
hmm pourquoi celui là il est gênant?
